# Назва додатка
spring.application.name=backend

# --- Налаштування PostgreSQL ---
spring.datasource.url={DB_URL}
spring.datasource.username={DB_USER}
spring.datasource.password={DB_PASSWORD}

# --- Налаштування JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
